document.addEventListener("DOMContentLoaded", function () {
    // Sayfanın adını alma
    const currentPage = window.location.pathname.split("/").pop();

    // Dinamik içerik alanını seçme
    const dynamicContent = document.getElementById("dynamic-content");

    // İçerikler
    const pageContents = {
        "balkanlar.html": `
            <h1>BALKANLAR TURU</h1>
            <img src="../img/balkanlarTur.png" alt="Balkanlar">
            <p>Makedonya, zengin tarihi ve doğal güzellikleriyle keşfedilmeye değer bir destinasyondur. Üsküp’ün tarihi köprüleri ve Osmanlı mirası, Ohrid Gölü’nün sakin suları ve etrafındaki tarihi yapılarıyla bu topraklar, gezginlere unutulmaz anlar vaat eder.</p>
            <h2>4 GECE 5 GÜN -  VİZESİZ TUR</h2>
            <h2>29 Ekim Özel Ajet Havayolları İle</h2>
            <h4>Tur Programı</h4>  <b>1. Gün: </b><span>İstanbul - Priştine</span>
            <p>İstanbul Sabiha Gökçen havalimanı gidiş terminali havayolu kontuarı önünde buluşma. AJet VF101 sefer sayılı uçuşu ile saat 13:25’de Kosova’nın başkenti Priştina’ya hareket. Rahat ve konforlu bir uçuşun ardından yerel saat ile 14:05‘de varış ve ülkeye giriş işlemlerinin ardından alanda bekleyen özel aracımız ile panoramik şehir turumuza başlıyoruz. Bu tur esnasında, Priştine’nin en önemli doğal güzelliklerinden biri olan Germia Parkı’nı ziyaret edeceğiz. Ardından, Kosova’nın kültürel mirasını sergileyen Kosova Müzesi’ni göreceğiz. Turumuz sırasında, Osmanlı dönemine ait birçok değerli yapıyı da ziyaret edeceğiz. Fatih Sultan Mehmed Camii’ni ve 18. yüzyıl eseri Yaşar Paşa Camii’ni göreceğiz. Şehrin tarihi mirası içinde yapacağımız bu gezi sırasında, 1389 Kosova Muharebesi sonucunda Kosova Ovası'nda öldürülen Osmanlı Padişahı I. Murad Hüdavendigâr'ın Türbesi'ni ziyaret ederek, bu önemli tarihi olayı ve Osmanlı tarihindeki yerini anma fırsatı bulacağız. Priştine’deki turumuzun ardından Otelimize transfer. Sonrasında Dileyen misafirlerimizle Prizren Turumuza katılıyoruz. Prizren turunun ardından priştine otelimize transfer. Geceleme otelimizde.</p>
            <b>2. Gün: </b> <span>Priştine - Tetova (Kalkandelen)  – Ohrid</span>
            <p>Sabah kahvaltımızın ardından valizlerimizi toplayıp, Makedonya'nın eşsiz doğası ve kültürel hazinelerini keşfetmek üzere yola çıkıyoruz. İlk durağımız, Makedonya'nın göz alıcı kasabalarından biri olan Tetova (Kalkandelen). Burada, Balkanların en renkli ve en etkileyici camilerinden biri olan Alaca Camii'yi ziyaret edeceğiz. 15. yüzyılda inşa edilen bu cami, dış cephesindeki canlı renkler ve detaylı süslemelerle sizi adeta büyüleyecek. Osmanlı mimarisinin bu nadide örneğini keşfederken, tarihin derinliklerine doğru bir yolculuğa çıkacağız. Tetova'daki ziyaretimizin ardından, yemyeşil dağlar ve masmavi göller eşliğinde Ohrid'e doğru yol alıyoruz. Yol boyunca Makedonya'nın nefes kesen manzaraları bize eşlik edecek. Ohrid’e varışımızla birlikte, Osmanlı'nın Balkanlar'daki önemli üslerinden biri olmuş tarihi Ohrid şehrini tanıtan bir tur gerçekleştireceğiz. Turumuz esnasında göreceğimiz yerler arasında: Kiril Alfabesini geliştirdiklerine inanılan 9. yüzyıl Bizans keşişleri Aziz Kirillos ve Metodios Anıtı, Aya Sofya Kilisesi, Roma döneminden kalma Antik Tiyatro gibi önemli yapılar yer alıyor. Ayrıca şehrin kalbi olan Çınar Meydanı'nda dolaşıp, eski Osmanlı döneminden kalma Türk Çarşısı'nı gezme fırsatımız olacak. Burada Halveti Tekkesi'ni ziyaret edebilir, şehrin kültürel dokusunu yakından hissedebilirsiniz. Ardından Yeni Çarşı ve Ohrid Pazarı'nı gezerek, yerel halkın günlük yaşamına tanık olacaksınız. Son olarak, Ohrid'in meşhur gölü ve gölün büyüleyici manzarası turumuza eşlik edecek. Turumuzun ardından Sonrasında Dileyen misafirlerimizle Ohrid Tekne Turumuza katılıyoruz. Tekne turumuzun ardından Otelimize transfer. Geceleme otelimizde.</p>
            <p>Priştine – Tetova (Kalkandelen): 128 km | Tetova (Kalkandelen) – Ohrid: 130 km <br>Toplam kat edilecek mesafe: 258 km <br><br> Ohrid Tekne Turu Kişi Başı 25 Eur</p>
            <p>Ohrid Eski Kenti çevresinde unutulmaz bir panoramik tekne turunun keyfini çıkarmaya hazır mısınız? Bu turda, kıyıya yakın seyrederken şehrin tarihi dokusunu ve büyüleyici manzaralarını yakından göreceğiz. Dönüş yolunda ise, kıyıdan daha uzağa açılarak tüm Eski Kent'in eşsiz panoramik manzarasını hayranlıkla izleyeceğiz. Göreceğimiz en önemli yerlerden biri, balıkçı yerleşimi Kaneo. Burada, 15. yüzyılın ortalarından kalma ve Ohri Gölü'ne bakan bir uçurumda yer alan Aziz John Kilisesi'ni keşfedeceğiz. Bu kilise, sadece tarihi değeriyle değil, aynı zamanda muhteşem konumu ve büyüleyici manzarasıyla da ünlüdür. Ohri'nin en çok fotoğraflanan ve en ikonik yapılarından biri olan bu kilise, bizlere harika fotoğraf fırsatları sunacak. Bu panoramik tekne turunda, gölün huzur veren sularında ilerlerken, Ohrid'in tarihi ve doğal güzelliklerinin tadını çıkaracağız. Her anı unutulmaz kılacak bu deneyim, tatilimizin en özel anılarından biri olacak.</p>
            <b>3. Gün: </b> <span>Ohrid </span>
            <p>Sabah kahvaltımızın ardından Resne-Manastır turuna, hareket ediyoruz. Bu Turumuzda Özel otobüslerimizle önce Resne’ye hareket ediyoruz. Yolumuz üzerinde bulunan ve İttihat ve Terakkinin en ünlü 3 simasından biri Resne’li Niyazi’nin Sarayını ziyaret ediyoruz. Ardından Manastır’a hareket ediyor ve Manastır(Bitola) kent gezimiz sırasında; Türk Çarşısını, Bedesten’i, İshak Camiini, Yeni Camii’ yi, ve gezinin en duygusal anlarını yaşayacağınız Atatürk’ün mezun olduğu Askeri İdadi’yi ve Atatürk Müzesi’ni ziyaret ediyoruz(Dışarıdan). Turumuzun ardından Ohrid’e geri dönüyoruz. Geceleme otelimizde.</p>
            <p>Ohrid – Resne : 36 km     |     Resne – Manastır: 33 Km   |   Manastır – Ohrid: 69 Km <br> Toplam kat edilecek mesafe: 138 km</p>
            <b>4. Gün: </b> <span>Ohrid – Üsküp </span>
            <p>Sabah kahvaltımızın ardından odaların boşaltılması ve Üsküp’e hareket. Üsküp’e varışa istinaden şehir turumuz başlıyor. Ünlü şairimiz Yahya Kemal Beyatlı’nın doğum yeri olan Üsküp’te göreceğimiz yerler arasında Mustafa Paşa Camii, Murat Paşa Camii, Kapan Hanı, Sulu Han ve Taş Köprüyü görüp, Vardar Nehrinin kıyısından ve nehrin karşı tarafında bulunan Türk ve Yahudi mahallelerini seyrederek yürüyüşümüze devam ediyoruz. Bu yürüyüşümüzde Makedonya Meydanı’nı, Osmanlı Köprüsü’nü ve Davut Paşa Hamamını dışarıdan görüp, Türk çarşına girecek Üsküp’ün sembol eserlerinden biri olan ve 16. yüzyılda inşa edilmiş Saat Kulesini, 14. yüzyılda yapılmış erken dönem camilerimizden Sultan Murat Camisini ve yine aynı yüzyıldan kalma İsa Bey Camini görüp, Türk çarşında serbest zaman veriyoruz. Serbest zamanın ardından otelimize transfer. Akşam eşsiz balkan müzikleri ve yemekleriyle süslenmiş, folklör ekibinin yöresel dans Showları ile eşsiz Balkan gecesi turumuz gerçekleşecektir. Geceleme Üsküp’de otelimizde.</p>
            <b>5. Gün: </b> <span>Üsküp – Priştine - İstanbul </span>
            <p>Sabah kahvaltımızın ardından Tüm gün serbest zaman. Rehberimizin belirleyeceği saatte havalimanına transfer oluyoruz. Uçağa biniş işlemlerinin ardından Ajet havayollarının VF102 tarifeli seferi ile saat 15:45’de İstanbul  Sabiha Gökçen havalimanına uçuşumuz gerçekleşecektir. Rahat ve konforlu bir uçuşun ardından saat 18:10’de İstanbul’a varış ve turumuzun sonu. Bir sonraki seyahatinizde tekrar görüşmek dileği ile sizlere veda ediyoruz.</p>
            <h4>Fiyata Dahil Olan Hizmetler</h4> <span> <i class="fas fa-plane"></i> Ajet Havayolları ile Sabiha Gökçen - Priştine – Sabiha Gökçen parkurunda gidiş-dönüş uçak biletleri<br><i class="fas fa-bed"></i> 4* Otel Kategorisinde 1 Gece Priştine, 1 Gece Üsküp ve 2 Gece Ohrid olmak üzere toplam 4 Gece Konaklama<br> <i class="fas fa-utensils"></i> Sabah Kahvaltıları<br></span>
            <h4>Fiyata Dahil Olmayan Hizmetler</h4><span><i class="fas fa-stamp"></i> Yurtdışı Çıkış Harç Pulu<br><i class="fas fa-shield-alt"></i> Seyahat Sigortası (65 Yaşa Kadar)<br><i class="fas fa-utensils"></i> Öğle-Akşam Yemekleri<br></span>
            <h4>Turdan Kareler</h4>
            <div class="gallery">
               <img src="../img/balkanlarGaleri1.png" alt="Balkanlar">
               <img src="../img/balkanlarGaleri2.png" alt="Balkanlar">
               <img src="../img/balkanlarGaleri3.png" alt="Balkanlar">
               <img src="../img/balkanlarGaleri4.png" alt="Balkanlar">
            </div>
            <h4>Tur Haritası</h4> <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3079020.4012722857!2d19.595580777007378!3d41.093995867090605!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1354159f70bc4809%3A0xe0f25ad6c81fc5b1!2sKuzey%20Makedonya!5e0!3m2!1str!2str!4v1734447428759!5m2!1str!2str" width="300" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            <h4><h4>Tur Ücreti</h4> 600 € Kişi Başı</h4>
            <h4>Rezervasyon Yapın</h4>   
        `,
        "fransa.html": `
            <h1>FRANSA TURU</h1>
            <img src="../img/fransaTur.png" alt="Fransa">
            <p>Paris, Fransa'nın en popüler turistik destinasyonlarından biridir. Eyfel Kulesi, Louvre Müzesi gibi ikonik yerleri keşfederek büyüleyici bir Paris deneyimi yaşayın.</p>
            <h2>3 GECE 4 GÜN </h2>
            <h2>Türk Havayolları ile</h2>
            <h4>Tur Programı</h4> <b>1. Gün: </b><span>İstanbul – Paris</span>
            <p>İstanbul Havalimanı Dış Hatlar Terminali Türk Hava yolları Kontuarı önünde buluşma. Bilet ve pasaport işlemlerinden sonra Türk Havayolları’nın TK1823 nolu rarifeli seferi ile Paris’e hareket ediyoruz. Yerel saat ile Paris’e varışımızı takiben Paris’e hareket ve panoramik şehir turu. Bu turumuzda Fransa’nın en önemli sembolü Eiffel Kulesi ilk görülecek yerler arasındadır. Sonrasında en şık kafeleri ve mağazaları ile ünlü Champs Elysees, Paris şehir manzarasını izleyebileceğimiz Zafer Meydanı ve Takı, Napolyon’un mezarı göreceğimiz yerler arasındadır. Tur sonunda otelimize transfer ve odalarımıza yerleşme ve serbest zaman. Dileyen misafirlerimiz ekstra olarak düzenlenecek Paris By Night turuna katılabilir. Tur sonrası Paris otele transfer. Gecele Otelimizde.</p>
            <b>2. Gün: </b> <span>Paris</span>
            <p>Otelde alacağımız  kahvaltının ardından serbest zaman. Dileyen misafirlerimiz ekstra olarak düzenlenecek Muhteşem Paris (Eiffel Kulesi + Seine Nehri Gezisi + Montmartre - Ressamlar Tepesi turuna katılabilir. Tur sonrası Paris otele transfer. Gecele Otelimizde.</p>
            <p>Ekstra tur : Muhteşem Paris (Eiffel Kulesi + Seine Nehri Gezisi + Montmartre - Ressamlar Tepesi </p>
            <p>Paris'in en önemli turistik mekanlarından oluşan kültürel içerikli bu turumuzda gün boyunca şehrin güzelliklerini keşfedeceğiz. Dümdüz bir ova üzerine kurulmuş görkemli Paris şehrinde güney yönünde ufka her baktığınızda bütün güzelliğiyle karşınıza çıkan, geceleri ışık şovlarıyla sizleri selamlayan şehrin sembolü, sanatçılara ilham kaynağı dünyaca ünlü Eiffel Kulesi gezimizde yüzyıllık asansörlerle ikinci kata ulaştığımızda Paris’i bu kez Eiffel kulesiz panoramik görüntüleri ile karşımızda bulacağız. Şehri yukarıdan seyretmenin zevkine vardıktan sonra, Paris’i tam ortasından kuzey ve güney (nehrin akış yönüne göre sağ ve sol yaka) olarak ikiye bölen Seine Nehri üzerinde tekne ile geziye çıkıyoruz. Paris'in en muhteşem binalarını yakından görecek, Seine Nehri’nin tüm köprülerinin altından geçerek unutulmaz anlar yaşayacaksınız. Bu tekne gezisi sırasında görülecek yerler arasında Fransız Enstitüsü, Millet Meclisi, Dışişleri Bakanlığı, Louvre-Orsay Müzeleri, Cite Adası, Adliye Sarayı, Conciergerie Hapishanesi, Belediye Sarayı, Alexander III Köprüsü günümüzü renklendirecek. Daha sonra sekizyüz yıllık Notre Dame Katedrali’nin ihtişamlı gotik mimarisini dışarıdan izleyeceğiz.Montmartre Tepesi’nden Paris’e hükmeden Sacrâ Coeur kilisesini ve 19. yüzyılın sonlarından beri Paris bohem hayatının merkezi olmuş Ressamlar tepesinin daracık tipik sokaklarını gezerken, ressamlara çizdireceğiniz portrenize de sahip olabilirsiniz.</p>
            <b>3. Gün: </b> <span>Paris</span>
            <p>Otelde alacağımız kahvaltının ardından serbest zaman. Dileyen misafirlerimiz ekstra olarak düzenlenecek Disneyland turuna katılabilirler.  Tur sonrası Paris otele transfer. Geceleme Otelimizde.</p>
            <p>Ekstra Tur : Disneyland turu : </p>
            <p>Paris’e 36 km uzaklıktaki Disneyland parkı gezimizde, Hayaletler evi, Mark Twain’in Gemisi, çılgın maden treni, Indiana Jones, Robinson’un evi, Karayip korsanları mağarası, bebekler dünyası, yıldızlar turu, 3 boyutlu sinema, uzaya yolculuk, denizaltı macerası, araba yarış pisti gibi aktivitelerle büyükler de en az küçükler kadar eğlenecek ve Disney karakterleriyle beraber gün boyunca çok keyifli anlar yaşayacağız…Disney karakterlerinin geçit törenini ve havai fişek gösterisini izledikten sonra sezona göre kapanış saatlerine uygun olarak Paris’e geri döneceğiz. Otelden hareket saati: 08:30 Parktan hareket saati: 18:00</p>
            <b>4. Gün: </b> <span>Paris - İstanbul</span>
            <p>Sabah kahvaltı serbest zaman. Rehberimizin belirleyeceği saatte havaalanına transfer oluyoruz. Türk Havayolları'nın  TK1834 nolu tarifeli seferi İstanbul'a hareket ediyoruz. Yerel  İstanbul Havalimanı'na varışımız ile turumuzun sonuna geliyoruz. Bir sonraki seyahatinizde görüşmek dileğiyle.</p>
            <p>Önemli Notlar<br>İlgili turumuz Münferit(Kişiye Özel) bir turdur. 1 kişi dahi olsa programda verilen hizmetler aynı şekilde gerçekleştirilmektedir.<br>Münferit Turlarımızda rezervasyon yapıldıktan hemen sonra biletleme yapılmaktadır. İptal & İade & Değişiklik durumlarında Havayollarının kuralları geçerlidir. </p> 
            <h4>Fiyata Dahil Olan Hizmetler</h4> <span> <i class="fas fa-plane"></i> Türk Havayolları tarifeli seferi ile İstanbul(İstanbul HL)-Paris(CDG) -İstanbul(İstanbul HL)- arası uçak bileti<br><i class="fas fa-bed"></i> Tercih edilen kategorideki otellerde 3 gece konaklama<br> <i class="fas fa-utensils"></i> Sabah Kahvaltıları<br></span>
            <h4>Fiyata Dahil Olmayan Hizmetler</h4><span><i class="fas fa-stamp"></i> Yurtdışı Çıkış Harç Pulu<br><i class="fas fa-shield-alt"></i> Seyahat Sigortası (65 Yaşa Kadar)<br><i class="fas fa-utensils"></i> Öğle-Akşam Yemekleri<br></span>
            <h4>Turdan Kareler</h4>
            <div class="gallery">
               <img src="../img/fransaGaleri1.png" alt="Fransa">
               <img src="../img/fransaGaleri2.png" alt="Fransa">
               <img src="../img/fransaGaleri3.png" alt="Fransa">
               <img src="../img/fransaGaleri4.png" alt="Fransa">
            </div>
            <h4>Tur Haritası</h4> <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d83998.77824487777!2d2.2646341324550456!3d48.85893843512504!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66e1f06e2b70f%3A0x40b82c3688c9460!2sParis%2C%20Fransa!5e0!3m2!1str!2str!4v1734445542559!5m2!1str!2str" width="300" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            <h4><h4>Tur Ücreti</h4> 500 € Kişi Başı</h4>
            <h4>Rezervasyon Yapın</h4>
        `,
        "istanbul.html": `
            <h1>İSTANBUL TURU</h1>
            <img src="../img/istanbulTur.png" alt="İstanbul">
            <p>İstanbul, tarih boyunca birçok medeniyete ev sahipliği yapmış, zengin kültürü ve boğaz manzarasıyla büyüleyen bir şehirdir. Ayasofya, Topkapı Sarayı ve Kapalıçarşı gibi tarihi mekanları keşfederken hem Doğu'nun hem de Batı'nın izlerini hissedin.</p>
            <h2>3 GECE 4 GÜN -  KÜLTÜR TURU </h2>
            <h2>3 Gece Otel Konaklaması & Otelden Günlük Gezi Ulaşımları & <br> Rehberlik & 3 Kahvaltı & Seyahat Sigortası Tur Ücretlerine Dahildir.</h2>
            <h4>Tur Programı</h4> <b>1. Gün: </b><span>İSTANBUL - SERBEST GÜN</span>
            <p>Misafirlerimizin Havalimanı veya Otogar 'a ulaşmalarının ardından, Otelimize gün içerisinde ulaşmasını takiben serbest dinlenme zamanı.  Konaklama Otelimizde.Talep edilmesi halinde : Atatürk Havalimanı, Sabiha Gökçen Havalimanı, Otel arasında geliş transferi ekstra ücret karşılığında verilebilmektedir. Transfer talebiniz kişi sayısına göre ayrıca fiyatlandırılmaktadır.</p>
            <b>2. Gün: </b> <span>DOLMABAHÇE SARAYI - FENER - BALAT – EYÜP SULTAN CAMİİ – PİERRE LOTİ TEPESİ - SÜLEYMANİYE CAMİİ</span>
            <p>Otelde alacağımız sabah kahvaltımızın ardından ilk durağımız olan Dolmabahçe Sarayı 'na hareket ediyoruz. Osmanlı imparatorluğunun günümüze ulaşan en görkemli sarayını ziyaret ettikten sonra Haliç kıyılarına hareket ediyoruz. Yabancıların Altın Boynuz ismi ile tanımladıkları İstanbul 'un en keyifli manzaralarından bir tanesi eşliğinde Haliç kıyılarında aracımız ile kısa bir seyahat gerçekleştiriyoruz. Bu seyahatimizde Haliç kıyısında bulunan Ortodoks Patrikhanesi , Tarihi Feshane binası , Mehterhane binaları gibi Fener , Balat semtinde öne çıkan eserlerini rehberimizin anlatımları ile panoramik olarak görüyoruz. Kısa seyahatimizin ardından her yıl milyonlarca insanın ziyaret ettiği   Eyüp Sultan Camii  ve Eyüp Sultan Hazretlerinin Türbesi geziyor ve ünlü Şair Pierre Loti ’nin adını alan ve manzara tepesine ulaşıyoruz. Burada Haliç manzarası eşliğinde çay molası veriyoruz. Çay molamızın ardından Süleymaniye semtine ulaşarak Süleymaniye Camii ve Kanuni Sultan Süleyman 'ın, Hürrem Sultan 'ın  türbesini ziyaret ediyoruz. Gezimizi burada tamamlayarak otelimize dönüyoruz. Tur dönüşü serbest zaman ve konaklama otelimizde.Extra Gece Turu imkanı : Grubumuzun talebine göre İstanbul Boğazında, Ekstra Yemekli Boğaz Turuna katılım.</p>
            <b> 3. Gün: </b> <span>TOPKAPI SARAYI – AYASOFYA – SULTANAHMET – DİKİLİTAŞ – YEREBATAN SARNICI - ARKEOLOJİ MÜZESİ - KAPALI ÇARŞI</span>
            <p>Otelde alacağımız sabah kahvaltımızın ardından Osmanlı'nın en büyük ve İstanbul ilk sarayı olan Topkapı Sarayı ’nı gezdikten sonra Bizans döneminin en önemli kilisesi, Osmanlı döneminde camii günümüzde müze olarak hizmet veren Ayasofya Müzesi 'ni geziyoruz. Daha sonra Hipodrom bölgesindeki Sultan Ahmet Camii , Dikilitaş , Yılanlı sütün, gezilerinin ardından Yerebatan Sarnıcı ve Arkeoloji Müzesi 'ni geziyoruz. Tur programımızı burada sonlandırıp size Kapalı Çarşı 'da kısa bir serbest zaman veriyoruz. Serbest zaman sonrasında tekrar toplanıyor ve otelimize dönüyoruz. Tur dönüşü serbest zaman ve konaklama otelimizde.Ekstra Gece Turu İmkanı : Grubumuzun talebine göre Ekstra Yemekli Türk gecesi Show programına katılım.</p>
            <b>4. Gün: </b> <span>İSTANBUL - SERBEST GÜN</span>
            <p>Otelimizde aldığımız sabah kahvaltımızın ardından serbest alışveriş zamanı veriyoruz. Öğlen saat 12:00 itibariyle odalarımızı boşaltarak. Dönüş saati daha geç olan misafirlerimiz eşyalarını emanete bırakarak arzularına göre alışveriş mekanlarında vakit geçirebilirler. Serbest zaman sonrası Otelden Havalimanına veya otogara hareket ile tur programının bitişi. Talep edilmesi halinde : Otelden, Atatürk Havalimanı yada Sabiha Gökçen Havalimanı 'na gidiş transferi ekstra ücret karşılığında verilebilmektedir. Transfer talebiniz kişi sayısına göre ayrıca fiyatlandırılmaktadır.</p>
            <p>Not  : Rehber havadurumu ve trafik gibi olumsuz şartlar nedeniyle programda görülecek yerler sıralamasında değişiklik yapabilir. Müzelerin kapalı günlerine tesadüf eden programlarda gezi programlarında değişiklik ve kaydırma yapılabilir.</p>
            <h4>Fiyata Dahil Olan Hizmetler</h4> <span> <i class="fas fa-bus"></i> Otelden hareketli, Gezi bölgelerine ulaşım<br> <i class="fas fa-bed"></i> 3 Gece Otel Konaklaması <br><i class="fas fa-utensils"></i>   3 Sabah kahvaltısı <br> <i class="fas fa-user-tie"></i> Profesyonel Rehberlik <br> <i class="fas fa-shield-alt"></i> Zorunlu Seyahat Sigortası</span>
            <h4>Fiyata Dahil Olmayan Hizmetler</h4> <span> <i class="fas fa-plane"></i>  İstanbul'a Geliş - Gidiş seyahati <br> <i class="fas fa-ship"></i> Tekne ile Yemekli Boğaz Turu ( extra gece turu ) <br> <i class="fas fa-utensils"></i>  Yemekli Türk Gecesi Show ( extra gece turu ) <br> <i class="fas fa-landmark"></i> Müze giriş ücretleri ve Müze Kart ücreti <br> <i class="fas fa-credit-card"></i> Kişisel harcamalar ve otel ekstraları</span>
            <h4>Turdan Kareler</h4>
            <div class="gallery">
               <img src="../img/istanbulGaleri1.png" alt="İstanbul">
               <img src="../img/istanbulGaleri2.png" alt="İstanbul">
               <img src="../img/istanbulGaleri3.png" alt="İstanbul">
               <img src="../img/istanbulGaleri4.png" alt="İstanbul">
            </div>
            <h4>Tur Haritası</h4> <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d385396.32109074044!2d28.68252805376745!3d41.00537021102762!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14caa7040068086b%3A0xe1ccfe98bc01b0d0!2zxLBzdGFuYnVs!5e0!3m2!1str!2str!4v1734445449338!5m2!1str!2str" width="300" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            <h4><h4>Tur Ücreti</h4> 800 € Kişi Başı</h4>
            <h4>Rezervasyon Yapın</h4>
        `,
        "italya.html": `
            <h1>İTALYA TURU</h1>
            <img src="../img/italyaTur.png" alt="İtalya">
            <p>Venedik, İtalya'nın kanallarıyla ünlü büyüleyici bir şehridir. Gondol turları ve San Marco Meydanı ile unutulmaz bir İtalyan deneyimi yaşayın.</p>
            <h2>3 GECE 4 GÜN </h2>
            <h2>Türk Hava Yolları İle Ekstra Turlar ve Çevre Gezileri Dahil</h2>
            <h4>Tur Programı</h4> <b>1. Gün: </b><span>İstanbul – Bologna - Venedik</span>
            <p>İstanbul Yeni Havaalanı Dış Hatlar Gidiş Terminali Türk Hava Yolları kontuarı önünde siz değerli misafirlerimiz ile saat 09:00’ da buluşuyoruz. Check-İn ve Bagajlarımızı teslim ettikten sonra Türk Hava Yolları’nın TK1323 numaralı tarifeli seferi ile 12:15’de Bologna’ya hareket ediyoruz. 13:55’de Bologna’ya vardıktan sonra Pasaport kontrolü ve Bagaj işlemlerimizden sonra Venedik’e doğru yola çıkıyoruz. Araçların son ulaşım noktası olan Tronchetto limanından vaporetto ile tarihi adaya hareket ediyoruz. Zevkli bir vaporetto yolculuğundan sonra şehrin tarihi merkezi olan San Marko Meydanına yakın bir noktada vaporetto'dan inerek kanallar arasındaki turumuza başlıyoruz. Motorlu araçlardan arındırılmış olan, polis, ambulans, çöp kamyonları, belediye otobüsleri vs. gibi günlük hayatta görmeye alışık olduğumuz bütün araçlar yerini teknelere bırakmış burada. Köleler sahilinden San Marko Meydanı'na yürürken Venedik hapishanesini ve hapishane ile Dükler Sarayını birbirine bağlayan "Ponte dei Sospiri" İç çekme köprüsü, köprünün tam karşısında San Giorgio Adası, Dükler Sarayının ana cephesindeki meydanda, şehrin giriş kapısı olarak adlandırılan ikiz kolonlar ve bu kolonlar üzerindeki Venedik'in sembolü olan heykelleri görebilirsiniz. San Marko Katedrali'nin bulunduğu meydan, Napolyon tarafından "Dünyanın en güzel meydanı" olarak adlandırılmıştır. Katedralin yapımı 9. yüzyılda tamamlanmış olsa da, bugünkü halini alması 17. Yüzyılı bulmuştur. Ana cephesinde göreceğiniz 4 adet bronz at, İkinci Haçlı Seferleri dönüşünde İstanbul'dan getirilmiştir. Serbest zamanınızda saat kulesinin tepesindeki heykellerin her saat başı çanın üzerine vurmalarını izleyip, Çan kulesine çıkarak bütün Venedik manzarasını tepeden de görebilirsiniz. Venedik Turumuzun ardından serbest zaman alıyoruz ve sonrasında konaklamak üzere Venedik otelimize doğru hareket ediyoruz. Geceleme Venedik otelimizde.</p>
            <b>2. Gün: </b> <span>Venedik – Floransa – Pisa - Montecatini</span>
            <p>Sabah kahvaltısı ardından Floransa'ya hareket. Varışın ardından Rönesans sanatının çıkış yeri olan, Avrupa ticaretinde ipek, yün, altın ve bankerlik konusunda öncülük yapmış olan, İtalyan Krallığı'na başkent olan, Dante, Leonardo da Vinci, Michelangelo gibi birçok önemli kişinin doğum yeri olan Floransa şehir turumuz başlıyor. Floransa Katedrali (Duomo), vaftizhane, çan kulesi, günümüzde açık hava müzesi olarak kullanılan Signoria Sarayı ve Meydanı, Lanzi Locası, Uffizi Meydanı, yaklaşık 650 senelik üzerinde kuyumcu dükkanlarının olduğu Ponte Vecchio, Cumhuriyet Meydanı, San Lorenzo Pazarı görülecek yerler arasındadır. Floransa turumuz ardından Pisa Şehrine doğru yola çıkıyoruz. Adını katedralin çan kulesine vermiş olan Pisa Kulesini görmenin yanı sıra, Pisa Katedrali, Avrupa'nın en görkemli vaftizhanesini ve de Mucizeler Meydanı'nı görüyoruz. Tur sonrası serbest zaman ve ardından otelinize transfer ve geceleme Floransa Montecatini bölgesindeki otelimizde.</p>
            <b>3. Gün: </b> <span>Floransa – Roma</span>
            <p>Sabah kahvaltısı ardından Roma’ya hareket ediyoruz. Dünya tarihinin ve İtalya'nın başkenti olan bu güzel şehirdeki turumuz esnasında, Roma şehri ve tarihinin doğduğu Forum Meydanı, Forum Meydanı’nın en meşhur caddesi olan ve Mussolini'nin kendine özel olarak açtırmasıyla ünlü Via Foridei Imperiali, Roma'nın kudret simgesi Colosseo Amfi tiyatrosu panoramik olarak görülecektir. Ardından düzenlenecek olan Melekler ve Şeytanlar turumuzda Roma'nın tamamını görme imkanını elde edeceksiniz. Melekler ve Şeytanlar turumuzda taş taş üstünde bırakmadan, yürüyerek ve araçlarımızı kullanarak her adım başı Roma’nın bir başka şaheserini görme imkanı bulabilirsiniz. Bu turumuzda ilk önce Roma'nın simgelerinden Venezia Meydanını, sonra ünlü mağazaların bulunduğu sokaklara açılan İspanyol Merdivenlerini ve İspanyol Meydanını geziyoruz. Daha sonra Fontana di Trevi'yi (Aşk Çeşmesi) , Phanteon , Piazza Popolo görülecek yerler arasındadır. Yemek için verilecek serbest zamanın ardından, 'a g Vatikan idiyoruz. Burada, dünyanın en büyük kilisesi olan San Pietro'da Rönesans'ın dev sanatçıları Leonardo Da Vinci ve Michelangelo'nun şaheserlerini gördükten sonra San Pietro Meydanını geziyoruz. Turumuzun ardından otelimize transfer ve odalarımıza yerleşme. Geceleme Roma'da otelimizde.</p>
            <b>4. Gün: </b> <span>Roma - İstanbul</span>
            <p>Sabah alınacak kahvaltımızın arından odaların boşaltılması rehberimizin belirleyeceği saatte hareket. Roma da Rehberimizin Belirlediği yer ve zamana göre serbest zaman. Akşamüzeri rehberimizin belirlediği saatte Roma havaalanına hareket. Türk Havayolları TK1864 tarifeli seferi ile saat 19:50'de İstanbul'a hareket. Rahat ve konforlu bir uçuşun ardından saat 00:20'de İstanbul Havalimanı'na varış ve turumuzun sonu. Bir sonraki organizasyonumuz da görüşmek dileği ile siz değerli misafirlerimize veda ediyoruz.</p>
            <p>Oteller<br>Roma- Park Hotel Villa Ferrata 3* vb. ve Ginevra Palace Hotel 3* vb.<br>Floransa - 4* Biondi Hotel Vb.<br>Venedik - 3* Le Calandre Hotel Vb</p>
            <h4>Fiyata Dahil Olan Hizmetler</h4> <span> <i class="fas fa-plane"></i> Türk Havayolları ile İstanbul - Bologna ve Roma - İstanbul Arası Gidiş Dönüş Ekonomi Sınıfı Uçak Bileti<br><i class="fas fa-bed"></i> Toplam 3 Gece Konaklama Hizmeti<br> <i class="fas fa-utensils"></i> Sabah Kahvaltıları<br></span>
            <h4>Fiyata Dahil Olmayan Hizmetler</h4><span><i class="fas fa-stamp"></i> Yurtdışı Çıkış Harç Pulu<br><i class="fas fa-shield-alt"></i> Seyahat Sigortası (65 Yaşa Kadar)<br><i class="fas fa-utensils"></i> Öğle-Akşam Yemekleri<br></span>
            <h4>Turdan Kareler</h4>
            <div class="gallery">
               <img src="../img/italyaGaleri1.png" alt="İtalya">
               <img src="../img/italyaGaleri2.png" alt="İtalya">
               <img src="../img/italyaGaleri3.png" alt="İtalya">
               <img src="../img/italyaGaleri4.png" alt="İtalya">
            </div>
            <h4>Tur Haritası</h4> <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12367340.84344755!2d2.1190867081576075!3d40.81982885131573!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12d4fe82448dd203%3A0xe22cf55c24635e6f!2zxLB0YWx5YQ!5e0!3m2!1str!2str!4v1734445365483!5m2!1str!2str" width="300" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            <h4><h4>Tur Ücreti</h4> 700 € Kişi Başı </h4>
            <h4>Rezervasyon Yapın</h4>
        `,
        "japonya.html": `
            <h1>JAPONYA TURU</h1>
            <img src="../img/japonyaTur.png" alt="Japonya">
            <p>Japonya, geleneksel tapınakları, modern şehirleri ve büyüleyici doğasıyla Asya'nın en popüler turizm merkezlerinden biridir. Unutulmaz bir tatil sizi bekliyor. </p>
            <h2>8 Gece Konaklama 10 Gün </h2>
            <h2>Miat Havayolları ile</h2>
            <h4>Tur Programı</h4> <b>1. Gün: </b><span> İstanbul – Ulan Bator-Tokyo</span>
            <p>Bugün  saat 13:00’de İstanbul Havalimanı, Dış Hatlar Gidiş Terminalinde buluşuyoruz. Bilet ve pasaport işlemlerinin ardından,MIAT Hava Havayolları’nın tarifeli saferi ile saat 16:20’de Ulan Bator aktarmalı olarak Japonya’nın başkenti TOKYO ‘ya hareket ediyoruz. Gecemiz uçakta geçiyor.</p>
            <b>2. Gün: </b> <span>Tokyo (NARITA)</span>
            <p>Saat 14:30’da Tokyo’ya varışımızın ardından alanda karşılanma ,şehir merkezine transferimiz yapılacaktır. Tokyo Şehir turumuza başlıyoruz.ASAKUSA tapınağı ve Ginza caddesi göreceğimiz yerler arasında. Turumuzun sonunda otelimize geçiyoruz.<br> Geceleme otelimizde.</p>
            <b>3. Gün: </b> <span>FUJI DAĞI-HAKONE TURU</span>
            <p>Bu sabah otelimizde alacağımız kahvaltı sonrası  serbest saatlerimiz başlıyor.. Arzu eden misafirlerimiz için Ekstra turumuz var. <br>HAKONE-FUJI YANARDAĞI- ASHİ GÖLÜ TURU TAM GÜN 200 USD ÖĞLE YEMEKLİ (japon Mutfağı) <br>Turumuz sabah 07:30 da otelimizden Özel Otobüsümüz ile başlıyor. Tam gün sürecek bu gezimizde Hakone/FUJİ dağı istikametine doğru yolculuğumuz başlıyor, rehberimizden Japonya hakkında bilgiler alıyoruz,  Fuji Dağı  eteklerine ulaşıyoruz, 5.İstasyon olarak bilinen noktaya çıkacağız, buradan FUJİ manzarasını izliyoruz. Daha sonra ÖĞLE YEMEĞİ molası veriliyor, bugün menüde JAPON Mutfağının özel lezzetleri var. ASHİ GÖLÜ kıyısına geçiyoruz, Japonya’nın kutsal göllerinden olan ve UNESCO koruması altına olan bu güzel yörede bir Tekne turuna katılıyoruz. Turumuzun bitiminde akşam saatlerinde TOKYO ‘ya döneceğiz.<br> Geceleme Otelimizde.</p>
            <b>4. Gün: </b> <span>TOKYO KAMAKURA -BAMBU BAHÇELERİ</span>
            <p>Bu sabah otelimizde alacağımız kahvaltı sonrası serbest günümüz olacak. Arzu eden misafirlerimiz extra turumuza katılabilirler.<br>Kamakura Dev Budha - Hokoku-jiTağınağı | Bambu Bahçeleri Tam Gün 145USD Öğle Yemekli * Geleneksel Japon Çayı servisi.<br>Bu sabah otelimizde alacağımız kahvaltı sonrası , otelimizden rehberimiz ile birlikte ayrılıyoruz. Kamakura Tokyo Körfezi bölgesine geçiyoruz, burada dev Budha Heykelini ziyaret edeceğiz, Ziyaretimiz sonrası , yine Japon inanışında çok öenmi yer tutan Hokoku Tapınağına ziyaretimizi yapacağız, Geleneksel mekanda Japon Çayını tadıyoruz, Öğle Yemeğimizi Japon Mutfağının özel lezzetlerinden tadarak alacağız, turumuzun son bölümünde Kamakura Bambu Bahçesini ziyaret ediyoruz, ve turumuzu tamamlayarak, Otelimize geri döneceğiz.<br> Geceleme Otelimizde.</p>
            <b>5. Gün: </b> <span>TOKYO</span>
            <p>Bu sabah otelimizde alacağımız kahvaltı sonrası serbest günümüz olacak <br> Geceleme TOKYO otelimizde.</p>
            <b>6. Gün: </b> <span>TOKYO-OSAKA uçuşu 08:30 09:25</span>
            <p>Bu sabah otelimizden ayrılıyoruz. Havalimanına  geçiyoruz. OSAKA uçuşumuzu yapacağız.PANAROMİK Osaka Turumuzu yapacağız, yaklaşık 2 saat sürecek turumuzun sonunda konaklayacağımız ,Otelimize ulaşıyoruz. Otele yerleştikten sonra Geceleme Otelimizde. OSAKA  GECE TURU (akşam yemeği) 100 USD Bu akşam Osaka’nın en yoğun mekanlarının olduğu sokakları gezeceğiz. Akşam yemeğimizi yerel bir japon restoranında alacağız.</p>
            <b>7. Gün: </b> <span>OSAKA - KYOTO- NARA TURU</span>
            <p>Bu sabah kahvaltıdan sonra serbest günümüz başlıyoruz. Misafirlerimiz extra turumuza katılabilirler. <br>TAM GÜN / ÖĞLE YEMEKLİ* KYOTO- NARA TURU  175 USD<br>Bu sabah 07:30 da otelimizden ayrılıyoruz, tur otobüsümüz ile Osaka şehrinin çevresinde yer alan üç önemli kenti ziyaret edeceğiz.<br>Yolculuğumuzun ilk durağı KYOTO şehir olacak , Kyoto’ya varışımızda şehri panoramik olarak geziyoruz. ShogunAshiagaYoshimitsu için Zen inancına göre inşa edilmiş Kinkakuji Mabedibir diğer adı ile ALTIN TAPINAK ziyaretimizi yapacağız.<br>Daha sonra Japon Mutfağı Açık BÜFE bir öğle yemeği bizleri bekliyor gezimizin devamında, ikinci durağımız NARA kenti olacak ve UNESCO Mirasları listesindeki TODAJİ tapınağını ziyaret ediyoruz, burada bahçesinde Nara geyiklerini de görüyoruz, serbestçe çevrede gezinmekteler.<br> Geceleme Osaka otelimizde </p>
            <b>8. Gün: </b> <span>OSAKA</span>
            <p>Bu sabah otelimizde alacağımız kahvaltı sonrası serbest günümüz olacak. <br>TAM GÜN * ARIMA ONSEN VE TAM GÜN KOBE TURU * 230 USD* <br>Öğle Yemeği Japon Mutfağı dahil <br>Geceleme OSAKA  otelimizde.</p>
            <b>9. Gün: </b> <span>OSAKA -TOKYO HIZLI TREN (SHINKANZEN) 08:00 -NARITA HAVALIMANI* Ulan Bator Uçuşu</span>
            <p>Bu sabah otelimizden tren istasyonuna geçiyoruz. Saatte 300 km hıza ulaşabilen SHINKANZEN Hızlı treni kullanarak  TOKYO ‘ya 2 saatte ulaşacağız , Burada  yerel tren hattı NARITA EXPRESS e  geçiyoruz ( aktarma) Bu  tren bizi  NARITA  Uluslararası havalimanına taşıyor. Bugün saat 15:30 ‘da  Ulan Bator uçuşumuz  olacak. Check in İşlemlerimizi yapıyoruz. Akşam MIAT HAVAYOLLARI ile Ulan Bator’a iniyoruz. 20:25. Bir gece konaklamak üzere şehirde otelimize geçiyoruz.<br> Geceleme Otelimizde.</p>
            <b>10. Gün: </b> <span>ULAN BATOR- ISTANBUL 10:00 14:30</span>
            <p>Sabah  havalimanına geçiyoruz. MIAT HavaYolları  tarifeli seferi ile ISTANBUL  uçuşumuzu yapacağız. Varış İstanbul 14:30 Turumuz  sona eriyor.</p>
            <h4>Fiyata Dahil Olan Hizmetler</h4> <span> <i class="fas fa-plane"></i> Miat Havayolları ile Uçak Biletleri Gidiş-Dönüş <br><i class="fas fa-bed"></i> Toplam 8 Gece Konaklama Hizmeti<br> <i class="fas fa-utensils"></i> Sabah Kahvaltıları<br></span>
            <h4>Fiyata Dahil Olmayan Hizmetler</h4><span><i class="fas fa-stamp"></i> Yurtdışı Çıkış Harç Pulu<br><i class="fas fa-shield-alt"></i> Seyahat Sigortası (65 Yaşa Kadar)<br><i class="fas fa-utensils"></i> Öğle-Akşam Yemekleri<br></span>
            <h4>Turdan Kareler</h4>
            <div class="gallery">
               <img src="../img/japonyaGaleri1.png" alt="Japonya">
               <img src="../img/japonyaGaleri2.png" alt="Japonya">
               <img src="../img/japonyaGaleri3.png" alt="Japonya">
               <img src="../img/japonyaGaleri4.png" alt="Japonya">
            </div>
            <h4>Tur Haritası</h4> <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d27816177.24611524!2d115.71071126621489!3d31.674091100374927!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x34674e0fd77f192f%3A0xf54275d47c665244!2sJaponya!5e0!3m2!1str!2str!4v1734443540655!5m2!1str!2str" width="300" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            <h4><h4>Tur Ücreti</h4> 1500 € Kişi Başı</h4>
            <h4>Rezervasyon Yapın</h4>
        `,
        "kuzeykibris.html": `
            <h1>KUZEY KIBRIS TURU</h1>
            <img src="../img/kuzeykibrisTur.png" alt="Kıbrıs">
            <p>Kuzey Kıbrıs, tarihi zenginlikleri ve doğal güzellikleriyle büyüler. Girne’nin tarihi kaleleri, Lefkoşa’nın kültürel dokusu ve Güzelyurt’un huzurlu doğası keşfe değer. Masmavi denizleri ve sakin atmosferiyle dinlendirici bir tatil vaat eder.</p>
            <h2>3 GECE 4 GÜN -  VİZESİZ TUR </h2>
            <h2>İstanbul Çıkışlı Uçaklı 3 Gece Otel Konaklamalı</h2>
            <h4>Tur Programı</h4> <b>1. Gün: </b><span>  Girne - Lefkoşa Turu</span>
            <p>Değerli konuklarımız Dış Hatlardan hareket edecek olan (SAW) İstanbul - Lefkoşa uçağı ile Lefkoşa’ya hareket ediyoruz. Lefkoşa’da bizi bekleyen aracımızla buluştuktan sonra Lefkoşa’ da Ledra Palace sınırını panaromik olarak görerek Girne Kapısından Lefkoşa Surlar içerisine giriyoruz burada önce Samanbahçe Evleri , Venedik Sütunu, Saray Meydanı, Büyük Han, Arasta Çarşısı, Lokmacı barikatı, Selimiye Camii (St. Sophia Katedrali) ve Bandabulya (Belediye Pazarı)’ nı ziyaret ediyoruz. Serbest zaman ardından gezimizi sonlandırıp Girne şehrine hareket ediyoruz. İlk önce Yol üzerinde bulunan Walt Disney kalesinin esinlendiği St. Hillarion Kalesi’ ni ziyaret ediyoruz. Buradan Girne Kalesi’ ni ziyaret edip ve meşhur Girne Antik Limanda Serbest Zaman veriyoruz. Gezimizi tamamladıktan sonra hotelimize dönüyor ve serbest zaman veriyoruz.</p>
            <b>2. Gün: </b> <span>Güzelyurt Turu</span>
            <p>Değerli konuklarımız Otelimizde alacağımız kahvaltının ardından hep birlikte adanın en yeşil bölgesi olan Güzelyurt’a hareket ediyoruz. Kaçakçının köşkü olarak ünlenmiş Mavi Köşkü ziyaret ediyoruz. Orta Doğunun en büyük silah kaçakçısının gizemli evinin sırlarını dinliyor, daha sonra Güzelyurt doğa ve arkeoloji müzesini ve hemen yanında St.Mamas Manastırını ziyaret ediyoruz. Buradan bölgenin ünlü portakal, Limon ağaçları eşliğinde Leakey’ye hareket ediyor, sabah kahvemizi, el yapımı Limonatamızı içip, Lefke ’nin sokaklarında eski Osmanlı konaklarını bölgenin ünlü hurma ağaçlarını görüp 1964 yılında Erenköy direnişi esnasında şehit düşen pilotumuz Cengiz Topel’in anıtını görüp Turumuzu bitirip otelimize doğru yola çıkıyoruz. </p>
            <b>3. Gün: </b> <span>Serbest Zaman</span>
            <p>Dileyen misafirler Otelde rehber arkadaşımızdan alternatif tur bilgisi alabilir.</p>
            <b>4. Gün: </b> <span>Gazimağusa – Kapalı Maraş</span>
            <p>Değerli konuklarımız Otelimizde alacağımız kahvaltının ardından Gazimağusa doğru yola çıkıyoruz. Önce St. Barnabas Manastırını ziyaret edip , sonra deniz kenarında bulunan Salamis harabelerini gidiyoruz. Antik Kıbrıs tarihi ve Meteoroloji hakkında bilgiler edindikten sonra artık misafirlerinizin içeriye girebildikleri Kapalı Maraş bölgesini girip bir zamanların Doğunu Parisi dedikleri dünyanın en meşhur ünlülerin rezervasyon yaptırdıkları otelleri görüp beraber yürüyerek keşfediyoruz. Sonra otobüsümüze dönüp Gazimağusa kalesinde ’ki gezimize başlıyoruz Lala Mustafa Paşa Cami , St Nicholas Katedrali , Venedik Sarayı , Namık Kemal zindanı görüp Mağusa kalesi içinde serbest zaman veriyoruz. Alışveriş ve Kıbrıs Tatlısı ( Ekmek Kadayıfı , Şeftali Kebabı ) Turumuzu bitirip Havalimanına doğru yola çıkıyoruz. Bir sonraki seyahatinde tekrar buluşmak üzere üzülerek vedalaşıyoruz. Hoşçakalın...</p>
            <h4>Fiyata Dahil Olan Hizmetler</h4> <span> <i class="fas fa-plane"></i> Pegasus ile Uçak Biletleri Gidiş-Dönüş<br><i class="fas fa-bed"></i> Toplam 3 Gece Konaklama Hizmeti<br> <i class="fas fa-utensils"></i> Sabah Kahvaltıları<br></span>
            <h4>Fiyata Dahil Olmayan Hizmetler</h4><span><i class="fas fa-stamp"></i> Yurtdışı Çıkış Harç Pulu<br><i class="fas fa-shield-alt"></i> Seyahat Sigortası (65 Yaşa Kadar)<br><i class="fas fa-utensils"></i> Öğle-Akşam Yemekleri<br></span>
            <h4>Turdan Kareler</h4>
            <div class="gallery">
               <img src="../img/kuzeykibrisGaleri1.png" alt="Kıbrıs">
               <img src="../img/kuzeykibrisGaleri2.png" alt="Kıbrıs">
               <img src="../img/kuzeykibrisGaleri3.png" alt="Kıbrıs">
               <img src="../img/kuzeykibrisGaleri4.png" alt="Kıbrıs">
            </div>
            <h4>Tur Haritası</h4> <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d833005.6732219942!2d32.99742155269566!3d35.357422916047014!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14de39d1bb42e217%3A0x744f55bc957b6540!2zS3V6ZXkgS8SxYnLEsXMgVMO8cmsgQ3VtaHVyaXlldGk!5e0!3m2!1str!2str!4v1734443436410!5m2!1str!2str" width="300" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            <h4><h4>Tur Ücreti</h4> 250 € Kişi Başı</h4>
            <h4>Rezervasyon Yapın</h4>
        `,  
        "misir.html": `
            <h1>MISIR TURU</h1>
            <img src="../img/misirTur.png" alt="Mısır">
            <p>Sharm El Sheikh, Mısır’ın en popüler tatil beldelerinden biridir. Muhteşem mercan resifleri ve berrak deniziyle dalış tutkunları için cennet niteliğindedir. Ayrıca, çöl safarileri ve tarihi kalıntılarla çevrili bölge, macera ve dinlenceyi bir arada sunar.</p>
            <h2>5 GECE 6 GÜN -  VİZESİZ TUR  Her Şey Dahil Oteller</h2>
            <h2>Ajet Havayolları ile</h2>
            <h4>Tur Programı</h4> <b>1. Gün: </b><span>  İstanbul – Sharm El Sheikh </span>
            <p>Sabiha Gökçen Havalimanı Dış Hatlar Gidiş Terminali’nde Ajet Havayolları kontuarı önünde  Çarşamba Akşamı 19:00’da buluşma. Bagaj ve bilet işlemlerimizin ardından Ajet Havayolları tarifeli uçuşu VF255 ile saat 22:10’da Mısır’ın egzotik tatil destinasyonu Sharm El Sheikh’e hareket. Çarşamba’yı Perşembe’ye bağlayan gece Yerel saat 00:55’de varışımızın ardından otelimize hareket. Misafirlerimiz tüm gün deniz, kum, güneşin keyfini çıkarabilirler. Geceleme otelimizde.</p>
            <b>2. Gün: </b> <span>Sharm El Sheikh </span>
            <p>Sabah otelde alınacak sabah kahvaltısının ardından serbest zaman. Sharm Şehir turu ve Çölde ATV/Buy Safari & Yıldızlar Altında Bedevi gecesi Turlarına katılıyoruz. Turlarımız sonrasında otele transfer. Geceleme otelimizde.<br>Ekstra Tur: Sharm Şehir Turu  (Yetişkin 25Usd / Çocuk 15Usd Kişi Başı)<br>Öğleden sonra başlayacak olan turumuzda cami, kilise Eski çarşı ve Naama bay Gezilecektir.</p>
            <p>Ekstra Tur: Çölde ATV/Buy Safari & Yıldızlar Altında Bedevi gecesi Turu <br>(Atv Tek Kişilik Araç Yetişkin 35 Usd Araç Başı)<br>(Atv İki Kişilik Araç Yetişkin 55 Usd Araç Başı)<br>(Buggy iki Kişilik Araç Yetişkin 65 Usd Araç Başı)<br>(Buggy Dört Kişilik Araç Yetişkin 105 Usd Araç Başı)<br>Macera ve adrenalin tutkunları için benzersiz bir deneyim. Çölü karış karış bilen profesyonel ekip liderlerimizi takip ederek çölün uçsuz bucaksız coğrafyasında hayatınız boyunca unutamayacağınız bir gezi sizleri bekliyor. Çölde bir Bedevi kampı ziyareti ve kampta naneli çay ikramı fiyata dahildir. Turumuzun ardında Günün 2 etabı olarak ise akşam Yıldızlar altında Bedevi Gecesini geçireceğimiz Bedevi kamp alanına yine atv ve Buggy araçlarımızla ulaşıyoruz. Sinai çölünde Deve yolculuğu ve Bedevi çayı, Geleneksel Bedevi akşam yemeği, Teleskop ile Yıldızlara ve gezegene bakma imkanı ile kaçırılmayak bir gün sizleri bekliyor. Bedevi gecesi bitiminde yine ATV ve BUGGY araçlarımızla Toplanma alanına dönerek otellere transferlerimiz otobüsler ile gerçekleşecektir.</p>
            <b>3. Gün: </b> <span>Sharm El Sheikh </span>
            <p>Sabah otelde alınacak sabah kahvaltısının ardından serbest zaman. Kahvaltı sonrasında arzu eden misafirlerimiz ile Ras Mohammed Tekne Gezisi Tam Gün/Öğle Yemekli Turuna katılıyoruz. Turlarımız sonrasında otele transfer. Geceleme otelimizde. </p>
            <p>Ekstra Tur: Ras Mohammed Tekne Gezisi Tam Gün/Öğle Yemekli (Yetişkin 35Usd / Çocuk 20Usd Kişi Başı)<br>(Dalış Dahil Yetişkin 45Usd / Çocuk 30Usd Kişi Başı)<br>Batıda Süveyş Kanalı, doğuda ise Akabe Körfezine bakan Ras Mohamed Milli Parkı, Kızıldeniz'in en güzel yerlerinden birisidir. Mangrov ağaçları, tuz göletleri, bakir plajları, doğal çöl yapısı, inanılmaz güzellikteki sualtı yaşamı ile Mısır'a gidenlerin mutlaka ziyaret etmek istedikleri yerlerden birisidir. Tam günlük ve öğle yemekli tekne gezimizde Ras Mohamed'in tüm güzelliklerinin tadını doyasıya çıkarabileceksiniz. Teknemizde, alkolsüz limitli içecekler ikram edilecektir. Dileyen misafirlerimiz rehberimize önceden haber vermek kaydı ile scuba dalış gerçekleştirebilirler.</p>
            <b>4. Gün: </b> <span>Sharm El Sheikh </span>
            <p>Sabah otelde alınacak sabah kahvaltısının ardından serbest zaman. Kahvaltı sonrasında arzu eden misafirlerimiz ile Tam Günlük Öğle Yemekli Kahire Pirmitler Turuna katılıyoruz. Turlarımız sonrasında otele transfer. Geceleme otelimizde.</p>
            <p>Ekstra Tur: Tam Günlük Öğle Yemekli Kahire Piramitler Turu<br>(Otobüs ile Yetişkin 75Usd / Çocuk 55Usd Kişi Başı)<br>(Uçak ile Yetişkin 235Usd / Çocuk 205Usd Kişi Başı)<br>Bu turumuz için otelden kahvaltı kutularımızı alıp, gece yarısından sonra otelimizden hareket ederek Kahire’ye gidiyoruz. Varışımızla birlikte ilk durağımız; Dünyanın 7 Harikasından günümüze kadar ulaşan tek eser olması ile dünyanın en çok merak edilen yerlerinden birisi olan Giza Piramitleri ve Sfenks. Turumuz boyunca Giza Platosu’nun en büyük piramidi olan sayısız gizemli teknik ve mimari unsuru yansıtan Keops Piramidi’ni, tüm platoyu ayakları altına alan Panorama Tepesini, Kefren, Mikerinos ve Kraliçe ile diğer soyluların anıt mezarları olan piramitleri görüp nefis fotoğraflar çekiyoruz. Sonrasında, Kefren Mezar kompleksinin en önemli parçası olan ve mumyalama işlemlerinin yapıldığı Kefren Vadi Tapınağı’nı ve Sfenks'i göreceğiz. Ardından, öğle yemeğimizi yerel bir restoranda alıyoruz. Gezimiz esnasında, Papirüs Atölyesi ve Doğal Parfüm Fabrikası ziyaretlerimiz de olacak. Sonrasında, dünyanın en ünlü ve önemli eserlerini ve üst katında dünyaca en çok ilgi görmüş keşif olan LuksoTutankhamon Mezarı Hazine’sini göreceğimiz Mısır Ulusal Müzesi’ni (giriş dahil) ziyaret edeceğiz. Ulusal Müze’nin alt katında Eski, Orta ve Yeni Krallık Dönemleri’nin en önemli ve değerli parçalarını, lahit ve heykellerini göreceğiz. Müze ziyaretimiz sonrası Afrika kıtasının en ünlü çarşısı olan Khan el Khalili Çarşısı'na gidiyoruz. Çarşı Amr İbn el As ile birlikte Kahire şehrinin kurucularından kabul edilen Muiz el din-Allah tarafından kurulmuş olan “Beyn-el Kasreyn” adı verilen “İki Saray arası” bölgesinin ve İslami Kahire’nin kalbinde yer alır. Dünyanın en eski ikinci medresesi olan El Ezher Medresesi adını taşıyan El Ezher Camii ve restore edilmiş haliyle Kahire’nin en güzel camilerinden Hüseyin Camii de burada yer alır. Çarşı ziyareti sırasında Hüseyin Camii’ni ziyaret edebilir, beş binin üzerinde dükkandan ve arastalardan birinde hediyelik alış-verişlerinizi yapabilir, Turumuzun ardından Otobüs ile Sharm’a geri dönüyoruz. </p>
            <b>5. Gün: </b> <span>Sharm El Sheikh </span>
            <p>Sabah otelde alınacak sabah kahvaltısının ardından saat 12:00 sularında Otelden çıkış işlemlerimizi gerçekleştiriyoruz. Valizlerimizi Valiz odasına bıraktıktan sonra tümgün serbest zaman. arzu eden misafirlerimiz ile SeaScope Yarı Denizaltı Turuna katılıyoruz. Turlarımız sonrasında otele transfer. Rehberimizin belirteceği transfer saatinde Sharm havalimanına Transfer oluyoruz. (yaklaşık 23:00 – 23:30 Sularında Transferimiz gerçekleşecektir)<br>Not: Oteli Transfer saatine kadar kullanmak isteyen misafirlerimiz için Aynı Turun 5gecelik seçeneği de mevcuttur)</p>
            <p>Ekstra Tur: SeaScope Yarı Denizaltı Turu  (Yetişkin 30Usd / Çocuk 20Usd Kişi Başı) <br>Teknemizin sualtında kalan cam bölümünde oturarak Kızıldeniz’in dünyaca meşhur ve akvaryum gibi olan sualtını içindeymişçesine deneyimleyip muhteşem fotoğraflar çekebilirsiniz. Turumuzun bitimiyle birlikte otele transfer.</p>
            <b>6. Gün: </b> <span>Sharm El Sheikh - İstanbul </span>
            <p>Havalimanına varışın ardından Bilet, bagaj ve uçuş işlemlerinin ardından Ajet Havayolları VF256 Sayılı tarifeli seferi ile Pazar Gününü pazartesi gününe bağlayan gece saat 03:35’da İstanbul’a hareket. Rahat ve konforlu bir uçuşun ardından saat 07:30’de  Sabiha Gökçen Havalimanına varış ve turumuzun sonu. Bir sonraki turumuz da görüşmek dileğiyle</p>
            <h4>Fiyata Dahil Olan Hizmetler</h4> <span> <i class="fas fa-plane"></i> Ajet ile Uçak Biletleri Gidiş-Dönüş<br><i class="fas fa-bed"></i> Toplam 5 Gece Konaklama Hizmeti<br> <i class="fas fa-utensils"></i> Sabah Kahvaltıları<br></span>
            <h4>Fiyata Dahil Olmayan Hizmetler</h4><span><i class="fas fa-stamp"></i> Yurtdışı Çıkış Harç Pulu<br><i class="fas fa-shield-alt"></i> Seyahat Sigortası (65 Yaşa Kadar)<br><i class="fas fa-utensils"></i> Öğle-Akşam Yemekleri<br></span>
            <h4>Turdan Kareler</h4>
            <div class="gallery">
               <img src="../img/misirGaleri1.png" alt="Mısır">
               <img src="../img/misirGaleri2.png" alt="Mısır">
               <img src="../img/misirGaleri3.png" alt="Mısır">
               <img src="../img/misirGaleri4.png" alt="Mısır">
            </div>
            <h4>Tur Haritası</h4> <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d112785.182590664!2d34.26635121239126!3d27.94683721963803!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14533bca3624d2e3%3A0xdd987e9c1945fd9c!2zxZ5hcm0gRWwtxZ5leWgsIFNlY29uZCBTaGFybSBBbCBTaGlla2gsIEfDvG5leSBTaW5hLCBNxLFzxLFy!5e0!3m2!1str!2str!4v1734441528474!5m2!1str!2str" width="300" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            <h4><h4>Tur Ücreti</h4> 300 € Kişi Başı</h4>
            <h4>Rezervasyon Yapın</h4>
        `,                       
        "yunanistan.html": `
            <h1>YUNANİSTAN TURU</h1>
            <img src="../img/yunanistanTur.png" alt="Yunanistan">
            <p>Atina, Yunanistan’ın tarihi ve kültürel mirasıyla ünlü başkentidir. Akropolis’te antik kalıntılar arasında tarihe yolculuk yapabilir, şehrin enerjik sokaklarında modern hayatı hissedebilirsiniz. Lycabettus Tepesi’nden gün batımını izlemek unutulmazdır.</p>
            <h2>3 GECE 4 GÜN </h2>
            <h2>Türk Havayolları ile</h2>
            <h4>Tur Programı</h4> <b>1. Gün: </b><span>  İstanbul - Atina </span>
            <p>İstanbul Yeni Havalimanı Dış Hatlar Terminali Türk Hava Yolları Kontuarı önünde saat 10:30’da buluşma. Bilet ve pasaport işlemlerinden sonra Türk Hava Yolları'nın tarifeli seferi TK1849 ile saat 13:50’de Atina'ya hareket ediyoruz. Yerel saatle 14:15’te Atina’ya varışımızın ardından panoramik Atina şehir turumuzu yapıyoruz. Agora, Zeus Tapınağı, Parlamento Binası, Syntagma ve Omonia Meydanları, Cumhurbaşkanlığı Sarayı, Başbakanlık Konutu, Tarihi Olimpiyat Stadyumu, Panepistimiou Bulvarları, Ulusal Kütüphane ve Akademi Üniversitesi panoramik olarak görülecek yerler arasındadır. Panoramik şehir turunun ardından serbest zaman. Ardından otelimize transfer. Geceleme Atina'daki otelimizde.</p>
            <b>2. Gün: </b> <span>Atina  </span>
            <p>Sabah otelde alınacak kahvaltının ardından serbest zaman. Arzu eden misafirlerimiz ekstra olarak organize edilecek Akropolis turumuza ve Korinth Kanalı turumuza katılabilirler. Akşam için ise ekstra olarak Pire, Paşa Limanı Gece Turu’na katılabilirler. Geceleme otelimizde.<br><br>Ekstra Tur: Akropolis Turu 35 Euro Kişi Başı<br>Atina Akropolisi, Atina'ya hakim yüksek bir kayalık üzerinde bulunan ve büyük mimari ve tarihi önemi olan birçok antik yapı kalıntısını içeren eski bir hisardır. Atina Akropolisi, tüm akropolislerin en bilineni olduğu için genellikle Akropolis denilince tüm dünyada ilk akla gelen yerdir.<br><br>Ekstra Tur: Nafplion ve Corint Kanalı Turu 70 Euro Kişi Başı<br>Yunanistan'ın en eski şehirlerinden biri olan Nafplion, Orta Çağ havasına sahip tatlı bir Peloponez (Mora Yarımadası) kasabasıdır. Ardından Korinth Kanalı, Yunanistan’ın kuzey kara topraklarını Mora Yarımadası’ndan ayıran, Ege ve Iyonya denizlerini birbirine bağlayan 6,5 km uzunluğunda yapay bir kanaldır. Süveyş Kanalı, Panama Kanalı, Tuna-Karadeniz kanalları gibi insan gücüyle yapılan ender kanallardan biridir.</p>
            <b>3. Gün: </b> <span>Atina  </span>
            <p>Sabah otelde alınacak kahvaltının ardından serbest zaman. Arzu eden misafirlerimiz ekstra olarak organize edilecek Patras turumuza katılabilirler. Akşam ise arzu eden misafirlerimiz rehberiniz tarafından düzenlenecek ekstra Yılbaşı Eğlencesi ve Yemeği Taverna Turu'na katılabilirler.<br><br>Ekstra Tur: Patras Turu 80 Euro Kişi Başı<br>Mora Yarımadası’nın en güzel tatil yerlerinden biri olan Patras, Yunanistan’ın 3. büyük şehridir. Patras’ta Ortaçağ Kalesi mutlaka görülmesi gereken yerlerden biridir. Tur sonrası otelimize transfer.<br><br>Ekstra Tur: Yılbaşı Eğlencesi Taverna Turu 150 Euro Kişi Başı <br>Akşam rehberiniz tarafından düzenlenecek ekstra Yılbaşı Eğlencesi ve Yemeği Taverna Turu'na katılabilirsiniz. MUTLU, SAĞLIKLI, BOL SEYAHATLİ YILLAR! Geceleme otelimizde.</p>
            <b>4. Gün: </b> <span>Atina - İstanbul  </span>
            <p>Sabah kahvaltı sonrası Atina Havalimanı'na hareket. Türk Hava Yolları'nın tarifeli seferi TK1850 ile saat 15:05’te İstanbul'a hareket ediyoruz. Check-in ve bagaj işlemlerinin ardından yerel saatle 17:35’te İstanbul Yeni Havalimanı'na varışımız ile turumuzun sonuna geliyoruz. Bir sonraki seyahatinizde görüşmek dileğiyle.<br><br>Önemli Uyarı<br>Ekstra turlar minimum 20 kişi olması durumunda gerçekleşmektedir. 20 kişinin altında olması durumunda fiyatlarda farklılık gösterebilir.<br><br>İptal Güvence Paketi: 50 Euro<br>İptal güvence paketi ile 10 iş günü kalana kadar tüm misafirlerimiz nedensiz, sebepsiz, şartsız turlarını iptal ettirebilir ve vize ile sigorta bedeli hariç tüm tur bedelini kesintisiz iade alabilirler.</p>
            <h4>Fiyata Dahil Olan Hizmetler</h4> <span> <i class="fas fa-plane"></i> Türk Havayolları Uçak Biletleri Gidiş-Dönüş<br><i class="fas fa-bed"></i> Toplam 5 Gece Konaklama Hizmeti<br> <i class="fas fa-utensils"></i> Sabah Kahvaltıları<br></span>
            <h4>Fiyata Dahil Olmayan Hizmetler</h4><span><i class="fas fa-stamp"></i> Yurtdışı Çıkış Harç Pulu<br><i class="fas fa-shield-alt"></i> Seyahat Sigortası (65 Yaşa Kadar)<br><i class="fas fa-utensils"></i> Öğle-Akşam Yemekleri<br></span>
            <h4>Turdan Kareler</h4>
            <div class="gallery">
               <img src="../img/yunanistanGaleri1.png" alt="Yunanistan">
               <img src="../img/yunanistanGaleri2.png" alt="Yunanistan">
               <img src="../img/yunanistanGaleri3.png" alt="Yunanistan">
               <img src="../img/yunanistanGaleri4.png" alt="Yunanistan">
            </div>
            <h4>Tur Haritası</h4> <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d50310.558977190805!2d23.69713961158742!3d37.990897659744455!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14a1bd1f067043f1%3A0x2736354576668ddd!2sAtina%2C%20Yunanistan!5e0!3m2!1str!2str!4v1734439472847!5m2!1str!2str" width="300" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            <h4><h4>Tur Ücreti</h4> 600 € Kişi Başı</h4>
            <h4>Rezervasyon Yapın</h4>
         `
    };

    // Sayfaya uygun içeriği yükleme
    dynamicContent.innerHTML = pageContents[currentPage] || "<p>Sayfa bulunamadı!</p>";
});